services:
  - type: web
    name: tap-to-earn-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tap-to-earn-db
          property: connectionString
      - key: BOT_TOKEN
        value: 8246236846:AAHW_hPy5wALCrnjip1iX_Gr-MnBYZneTko
